name: Build & Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  call-docker-release:
    uses: OperationsPAI/shared-workflows/.github/workflows/release-docker.yml@main
    with:
      caller: ${{ github.event.repository.name }}
      volces_name: pair/rcabench-frontend
    secrets: inherit
