name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'
      - '.github/workflows/release-helm.yml'
    tags:
      - 'v*'

jobs:
  call-helm-release:
    uses: OperationsPAI/shared-workflows/.github/workflows/release-helm.yml@main
    with: 
      repo_name: AegisLab-frontend
      repo_url: https://operationspai.github.io/AegisLab-frontend/
      tag_push: ${{ startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit